### ISSUE TITLE
Improvement:getNormalizingPathIterator

### ISSUE THREAD

**Issue by mkarg** [bourgesl/marlin-renderer#11]
I'd llike to propose to make this method static...

PathIterator getNormalizingPathIterator(final RendererContext rdrCtx,
                                            final NormMode mode,
                                            final PathIterator src)

...as I do not see any reason not to be static already.

Also I would recommend to replace the implementation by simply...

return mode.getNormalizingPathIterator(rdrCtx, src)

...as (in theory) this shorter code will get inlined while a rather complex switch won't.

**Comment by bourgesl** [comment]
It seems a good idea and will try adopting your approach soon

**Comment by bourgesl** [comment]
It seems a good idea and will try adopting your approach soon

**Comment by bourgesl** [comment]
Fixed in commit:
https://github.com/bourgesl/marlin-renderer/commit/3dd0250cd23109d32d83e40cbd5c62721459ed19

**Comment by mkarg** [comment]
Cool. 8-)
