### ISSUE TITLE
java.lang.SecurityException is thrown when initializing class org.marlin.pisces.OffHeapArray in version 0.7.4 build 2

### ISSUE THREAD

**Issue by kbotond** [bourgesl/marlin-renderer#12]
The exception is thrown in line number 59 of OffHeapArray.java:
`        UNSAFE   = Unsafe.getUnsafe();`

This call is supposed to throw a SecurityException, that is why the Unsafe instance is obtained reflectively a few lines earlier:
```java
        Unsafe ref = null;
        try {
            final Field field = Unsafe.class.getDeclaredField("theUnsafe");
            field.setAccessible(true);
            ref = (Unsafe) field.get(null);
        } catch (Exception e) {
            MarlinUtils.logInfo("Unable to get sun.misc.Unsafe; exit now.");
            System.exit(1);
        }
```

The value of `ref` should be assigned to `UNSAFE`, like in previous Marlin versions.

**Comment by bourgesl** [comment]
You're right. 
It is an annoying merge issue !!

Will fix later today

**Comment by bourgesl** [comment]
Fixed and jar files updated:
https://github.com/bourgesl/marlin-renderer/releases/tag/v0.7.4_2

Laurent

**Comment by kbotond** [comment]
Thanks, it works now. The source jar still contains the wrong version though.

**Comment by bourgesl** [comment]
Yes as I just uploaded new jar files.
I was lazy to make a new release that creates a new tag and proper source files.
