### ISSUE TITLE
Gamma value

### ISSUE THREAD

**Issue by Sciss** [bourgesl/marlin-renderer#13]
I'm trying to solve a problem I have in IntelliJ where anti-aliased fonts with slight (low) hinting show too think font outlines when using a bright-on-dark colour scheme (e.g. white text on blueish background). In black-on-white scheme, the font anti-aliasing is good for me. This makes me think the main issue here is an unsuitable gamma value for the anti-aliasing colours.

Is there a way to tune marlin-renderer to use a different gamma value? Some like (hypothetical)

    -Dsun.java2d.renderer=sun.java2d.marlin.MarlinRenderingEngine
    -Dsun.java2d.renderer.gamma=0.8

It seems this settings _exists_, but the effect is none. For example 0.5:

![screenshot from 2017-04-11 14-49-43](https://cloud.githubusercontent.com/assets/131300/24910133/0351e1c8-1ec7-11e7-8f22-410e47a8057c.png)

versus 2.0:

![screenshot from 2017-04-11 14-52-45](https://cloud.githubusercontent.com/assets/131300/24910138/0a2472c2-1ec7-11e7-83e1-a6273402efa2.png)

The colours look exactly the same, the font is too thick.

**Comment by bourgesl** [comment]
Marlin is dedicated to shape rendering, so it does not handle font rendering: it is the scope of the font rasterizer (except if you convert your glyph vectors to shapes).

Finally the gamma correction in Marlin is still experimental: it only tweaks the alpha coverage values but it is 'fake' corrections.

The real issue relies in the JDK (java2d software / ogl / d3d loops) that does not perform the gamma correction at the blending stage of Shape's alpha coverage masks (in JavaFX it could be implemented by a shader).

For fonts, you should look into freetype, jdk's gamma correction...

Laurent

**Comment by Sciss** [comment]
Oh ok, sorry then for the wrong place.
