### ISSUE TITLE
java.lang.NoSuchFieldError: refList when using 0.9.2 with Intelllij - Java 8

### ISSUE THREAD

**Issue by IceMan81** [bourgesl/marlin-renderer#28]
Tried the latest 0.9.2 with Intellij and I get the following error.
Caused by: java.lang.NoSuchFieldError: refList
	at sun.java2d.d3d.D3DRenderQueue.flushBuffer(D3DRenderQueue.java:157)
	at sun.java2d.d3d.D3DRenderQueue.flushAndInvokeNow(D3DRenderQueue.java:142)
	at sun.java2d.d3d.D3DRenderQueue.getInstance(D3DRenderQueue.java:53)
	at sun.java2d.d3d.D3DGraphicsDevice.getDeviceCaps(D3DGraphicsDevice.java:108)
	at sun.java2d.d3d.D3DGraphicsDevice.createDevice(D3DGraphicsDevice.java:87)
	at sun.awt.Win32GraphicsEnvironment.makeScreenDevice(Win32GraphicsEnvironment.java:235)
	at sun.java2d.SunGraphicsEnvironment.getScreenDevices(SunGraphicsEnvironment.java:181)
	at sun.awt.Win32GraphicsEnvironment.getDefaultScreenDevice(Win32GraphicsEnvironment.java:118)
	at java.awt.Window.initGC(Window.java:476)

If I switch back to 0.9.1 there are not issues.

Intellij settings relevant to Marlin-render

-Xbootclasspath/a:C:\Programs\marlin\marlin-0.9.2-Unsafe.jar
-Xbootclasspath/p:C:\Programs\marlin\marlin-0.9.2-Unsafe-sun-java2d.jar

sun.java2d.renderer=sun.java2d.marlin.DMarlinRenderingEngine
sun.java2d.renderer.subPixel_log2_X=8
sun.java2d.renderer.subPixel_log2_Y=5
sun.java2d.renderer.tileSize_log2=7
sun.java2d.renderer.tileWidth_log2=6
sun.java2d.renderer.useSimplifier=true

**Comment by bourgesl** [comment]
Hi,

Jetbrains JRE already hacked the mentioned class.

To avoid any conflict with Marlin java2d patch, just remove the option:
-Xbootclasspath/p:C:\Programs\marlin\marlin-0.9.2-Unsafe-sun-java2d.jar

Laurent

Le mer. 16 mai 2018 à 22:37, Gesly George <notifications@github.com> a
écrit :

**Comment by bourgesl** [comment]
In Marlin 0.9.2, I added the following classes included in the optional marlin-0.9.2-Unsafe-sun-java2d.jar:
- sun.java2d.pipe.RenderQueue
- sun.java2d.opengl.OGLRenderQueue

JetBrains JRE includes patched RenderQueue (in some releases), so the conflict happens.

Finally, I will propose soon a new pull request to JetBrains JDK8u to upgrade to the latest Marlin renderer.

Depending on the JetBrains JRE you have, it already has either Marlin 0.7.5 or Marlin 0.9.1 (build > 1153.2).

**Comment by bourgesl** [comment]
Finally, I could package these specific RenderQueue classes into another jar file to avoid any conflict in the future.
What do you think ?

**Comment by bourgesl** [comment]
I am preparing a pull request to Jetbrains JDK8 to upgrade Marlin 0.9.2 so I will not make any change on Marlin releases.
For  Jetbrains JRE, do not include marlin-0.9.2-Unsafe-sun-java2d.jar as a workaround.

**Comment by bourgesl** [comment]
Pull request merged:
https://github.com/JetBrains/jdk8u_jdk/commits/master

**Comment by IceMan81** [comment]
@bourgesl  It looks like the problem still persists - the issue is using -Xbootclasspath/p:C:\Programs\marlin\marlin-0.9.2-Unsafe-sun-java2d.jar

**Comment by bourgesl** [comment]
As explained before, Marlin releases provide 2 jars but you must use only marlin-0.9.2-Unsafe.jar with JetBrains JDK8.
Never put marlin-0.9.2-Unsafe-sun-java2d.jar !
or use only jetbrains jdk8 that already provide the Marlin renderer ...

**Comment by IceMan81** [comment]
Sorry, for some reason I was under the impression that once marlin 0.9.2 was merged into intellij-Jdk I could continue to use the marlin unsafe sun jar. Thanks for clearing that up.
