### ISSUE TITLE
Canvas support?

### ISSUE THREAD

**Issue by chengenzhao** [bourgesl/marlin-renderer#29]
Is there any canvas support of this renderer
like canvas.drawImage(image, x, y); etc.
if so, we could make a game engine based on canvas^_^

**Comment by bourgesl** [comment]
This renderer concerns only shape rendering in Java 2D so it only implements Java's RenderingEngine interface. 
It does not provide a generic renderer (complete graphics stack) like java Graphics2D or javafx Canvas API
