### ISSUE TITLE
0.5.7 was tagged on master, not use_Unsafe

### ISSUE THREAD

**Issue by Ben-Mann** [bourgesl/marlin-renderer#3]
I notice the tag is on commit 28fecc09 from master - was it built from the wrong branch also?

**Comment by bourgesl** [comment]
You're right: I tagged the wrong branch but the release package are the good ones

**Comment by bourgesl** [comment]
Use the following commit on the branch Use_Unsafe (march 11th):
db30034f4472e945230a61b1df2c7f00b342ab34
