### ISSUE TITLE
Marlin causes VisualVM to hang

### ISSUE THREAD

**Issue by cowwoc** [bourgesl/marlin-renderer#30]
Hi,

Can you please take a look at the discussion at https://github.com/oracle/visualvm/issues/101#issuecomment-410430741 ? It seems that the Marlin engine is going into some sort of endless loop, causing VisualVM to hang.

**Comment by bourgesl** [comment]
Please try jdk11-ea or marlin 0.9.2 module patch for jdk10 to test if your problem is fixed in the latest release.
Without detailled instructions on how to reproduce your problem, it is impossible for me to diagnose it properly.

**Comment by bourgesl** [comment]
WONT-FIX
