### ISSUE TITLE
Marlin 0.9.x hangs in busy infinite loop in Dasher.lineTo() drawing a large line

### ISSUE THREAD

**Issue by Matze2** [bourgesl/marlin-renderer#31]
Build and execute the following class using OpenJDK8 with marlin-0.9.3-Unsafe.jar:
[EndlessLoop.java.txt](https://github.com/bourgesl/marlin-renderer/files/2555437/EndlessLoop.java.txt)

I used the following OpenJDK variant on OpenSUSE Leap 42.3:
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (IcedTea 3.9.0) (build 1.8.0_181-b13 suse-27.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```
It hangs forever consuming 100% CPU in line 29: g2.draw(line)

Changing line 27
`				Line2D line = new Line2D.Double(10, 10, 0, 4e7);`
to a smaller value like
`				Line2D line = new Line2D.Double(10, 10, 0, 1e7);`
does not block and reaches line 30 within a second.

**Comment by bourgesl** [comment]
Could you give your command line to let me know which Marlin renderer and settings you use ?

It is surely related to a numerical precision issue when clipping the segment to the clip rectangle: I will see how to ensure clipped parts are outside the clip...

Thanks for your feedback,
Laurent

**Comment by Matze2** [comment]
Here you are. Since I am in the office now this time using Windows and AdoptOpenJDK 
```
C:\Program Files\Java\jdk8u192-b12\jre\bin>.\java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_192-b12)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.192-b12, mixed mode)
```
The command line I used is
```
"C:\Program Files\Java\jdk8u192-b12\bin\java.exe" -Dsun.java2d.renderer=org.marlin.pisces.MarlinRenderingEngine -Xbootclasspath/a:C:\Users\matze\Downloads\marlin-0.9.3-Unsafe.jar -classpath C:\Users\matze\eclipse-workspace\simple\target\classes matze.EndlessLoop
```

Side note that you understand from where we came:
Initially we had the problem that JFreeChart was calling Dasher.lineTo(NaN, NaN) which also blocked with Pisces. This was the reason why we are trying Marlin now.
Of course nobody would draw a line of this size by intention but having a thread cycling with 100% CPU when triggering this scenario can be critical for the whole host when you think about web applications.

**Comment by bourgesl** [comment]
Of course, I will fix that problem soon.
FYI I recommend using Marlin double precision (default in jdk10):
Dsun.java2d.renderer=org.marlin.pisces.DMarlinRenderingEngine
Hope it is a workaround for now

**Comment by bourgesl** [comment]
Double vs Float ~ 1% perf difference, but higher quality on x86 64bits processors.

I never made any benchmark on 32bits or embedded systems (pi, arm, powerpc...)

Anyway this numerical issue is still possible but for larger numbers with double values.
I will test with increasing line length to establish the limit.

**Comment by bourgesl** [comment]
Do you confirm that your problem do not happen with Marlin Double precision ?

It gives me more time to fix the precision issue...

**Comment by Matze2** [comment]
Yes it works with DMarlinRenderingEngine for these values but of course takes some time.

Here some numbers:

Drawing a line to y=4.0E7
1541670292910: If you don't see 'Not hanging.' then you hang :)
1541670295111: Not hanging.
_Around 2 seconds for 4.0E7._

Drawing a line to y=1.0E8
1541670374510: If you don't see 'Not hanging.' then you hang :)
1541670379637: Not hanging.
_Around 5 seconds for 1.0E8._

Drawing a line to y=1.0E9
1541670807124: If you don't see 'Not hanging.' then you hang :)
1541670855332: Not hanging.
_Around 48 seconds for 1.0E9._

So even if it is not hanging infinitely it can take arbitrarily long on erratic values. Therefore it would be best to only draw the portion that is "visible". Not sure if something like this is possible.

After some discussion with my colleagues we will use DMarlinRenderingEngine anyway. So this constructed case is not an issue for us, i.e. not urgent.

**Comment by bourgesl** [comment]
Thanks for the information.

Marlin 0.9.3 performs path clipping in dasher so it should only emit dashes for the visible portion, already.
Your timings make me think that the long clipped line is not properly ignored due to the numerical precision issue, we talked about.
I will definitely study this interesting case,
Thanks

**Comment by bourgesl** [comment]
I took few minutes to check your problem and your test does not use Marlin renderer as RenderingHints.VALUE_ANTIALIAS_ON is missing !

[EndlessLoop.java.txt](https://github.com/bourgesl/marlin-renderer/files/2562682/EndlessLoop.java.txt)

I fixed the test to use larger length (up to 7e15) and Marlin renderer rocks (both Float/Double variants) on JDK8:
- noAA ie not Marlin renderer (native C renderer ?) 
drawLine(1.0E8) [AA=false]: 3631.4947909999996 ms.
- AA org.marlin.pisces.DMarlinRenderingEngine:
drawLine(1.0E8) [AA=true]: 42.381105 ms.
drawLine(1.0E8) [AA=true]: 1.86741 ms.
- AA org.marlin.pisces.MarlinRenderingEngine:
drawLine(1.0E8) [AA=true]: 50.357248999999996 ms.
drawLine(1.0E8) [AA=true]: 1.935198 ms.
drawLine(7.0E15) [AA=true]: 48.779185999999996 ms.
drawLine(7.0E15) [AA=true]: 1.946686 ms.

Marlin path clipper is working like a charm !

**Comment by Matze2** [comment]
Confirmed. Sorry, I was not aware that I have to give also the "antialiasing" hint on top of of boot classpath and system property.

I could not find a place where this is documented that only the hint "really" enables the renderer.
Maybe this should be added to the "How to use" page.

In our case we just need to find a why how to enable antialiasing in all cases since in our scenario we do not access Graphics2D directly but behind libraries like JFreeChart in our case.

But issue itself is of course solved and can be closed. Thank you very much for your help!

**Comment by bourgesl** [comment]
See Marlin renderer description:
"Marlin is the FAST Java2D antialiasing rasterizer derived from OpenJDK Pisces (shape) "

For JFreechart, it is easy (since 2005):
Map hints = new HashMap();
hints.put(RenderingHints.KEY_ANTIALIASING,
...
chart.setRenderingHints(new RenderingHints(hints));

PS: what is your application ? (public ?)

**Comment by Matze2** [comment]
No not public. 
This is currently on research about the general strategy what we will do with Java 8 in 2019.
