### ISSUE TITLE
Thin lines in PDF not rendered

### ISSUE THREAD

**Issue by gitdode** [bourgesl/marlin-renderer#36]
We have a PDF here that contains a form with graphs with very thin lines. When rendered with ICEpdf with Oracle JDK 8 (Ductus), the graphs are rendered correctly. With OpenJDK 8 (Pisces), the graphs are only rendered when we zoom in to about 600%. With Marlin, the graphs show up at 150% zoom factor.

The issue can be worked around in ICEpdf by setting
`
-Dorg.icepdf.core.strokeAdjustmentEnabled=true
-Dorg.icepdf.core.strokeAdjustmentThreshold=1f 
-Dorg.icepdf.core.strokeAdjustmentValue=1f
`
As far as I understand, this will basically force a minimum line with of 1. With Pisces and this workaround however the graphs disappear again when zooming out below 70%.
And of course, the lines are thicker than they are supposed to be.

Debugging MarlinRenderingEngine, execution steps into line 208:
`widthScale = (float)Math.sqrt(at.getDeterminant());`
In our scenario, at.getDeterminant() returns the value -0.47389273965262657 and widthScale and thus the value returned by userSpaceLineWidth(AffineTransform, float) is NaN.

Using the absolute value of at.getDeterminant(), the lines seem to get rendered correctly, the value returned by userSpaceLineWidth(AffineTransform, float) then is 0.18158083 - but I have no idea if this is a correct solution :-)

Sorry I have not been able to reproduce the issue like it is done here: https://bugs.openjdk.java.net/browse/JDK-6829673

But I'll attach the PDF that reproduces the problem with ICEpdf Viewer: https://www.icesoft.org/wiki/display/PDF/Viewer+RI
[GraphsWithThinLines.pdf](https://github.com/bourgesl/marlin-renderer/files/3534750/GraphsWithThinLines.pdf)

Please let me know if I can provide more infos or help with testing etc.

Cheers,
Torsten

**Comment by bourgesl** [comment]
Hi,

Thank you for your feedback and your analysis, the reproducer code will
absolutely help me fixing this problem.

I already fixed many precision and NaN issues in Pisces code that happen in
corner cases. I think you found another flaw.

I will have a look soon once I am back from holidays (early next week).

Cheers,
Laurent

Le ven. 23 août 2019 à 15:51, Torsten Römer <notifications@github.com> a
écrit :

**Comment by bourgesl** [comment]
Hi,
I reproduced your problem and tested several solutions.

The determinant is negative because the transform has the flip bit.
I checked the correct solution consists in using the absolute value.

See the commit in my dev branch:
https://github.com/bourgesl/marlin-renderer/commit/9f10634108a03a59b2d1cb6698dd803fa1064556

It will take time to provide an openjdk patch with a new regression test...

Thanks,
Laurent

Le sam. 24 août 2019 à 10:02, Laurent Bourgès <bourges.laurent@gmail.com> a
écrit :

**Comment by gitdode** [comment]
Hi Laurent,

Thank you for the quick solution!

If you like I can try to create a regression test - do you have a somewhat similar test that I could use as a starting point?

Cheers,
Torsten

**Comment by bourgesl** [comment]
Thanks tosten.
You can derive a new test from:
https://github.com/bourgesl/marlin-renderer/blob/use_Unsafe/src/test/java/DashedRectTest.java

It must be a standalone class (jtreg), just set the complex transform and draw few thin lines.
 Use checkPixel() to decide if the test pass according to 1 or 2 pixel colors.
Without the fix, pixels will stay white (blank), with the fix, some will be painted != white.

Anyway I will do it to propose a new openjdk patch (14 then 11u backport)...

Laurent

**Comment by gitdode** [comment]
I had given it a try already, I'll attach the test - it seems to work but I have to admit I had to do some try and error to get into the condition where the issue occurred. But maybe it is useful anyway.
[FlipBitTest.java.txt](https://github.com/bourgesl/marlin-renderer/files/3554332/FlipBitTest.java.txt)

Thanks again,
Torsten

**Comment by bourgesl** [comment]
That looks very good, I will try it asap and add some debugging code...
Thanks

**Comment by bourgesl** [comment]
Test integrated:
https://github.com/bourgesl/marlin-renderer/commit/fca7ba8197a66e774092fef41abdbff7855a0c93

**Comment by bourgesl** [comment]
See JBS:
https://bugs.openjdk.java.net/browse/JDK-8230728

**Comment by bourgesl** [comment]
Fixed in release 0.9.4.2:
https://github.com/bourgesl/marlin-renderer/releases/tag/v0_9_4_2

**Comment by gitdode** [comment]
Hi Laurent,

since you mentioned a 11u backport and there is jdk11-fix-request for [JDK-8230728](https://bugs.openjdk.java.net/browse/JDK-8230728), will the fix really go into JDK11? That would be very nice.

Thanks,
Torsten

**Comment by bourgesl** [comment]
I am still waiting for backport approval ie jdk11-fix-request-yes ...
Let's wait and see.

**Comment by bourgesl** [comment]
Pushed in jdk11u:
https://bugs.openjdk.java.net/browse/JDK-8231621 (11.0.5)

**Comment by bourgesl** [comment]
Wrong push. It should be part of 11.0.6 (2020.01)
