### ISSUE TITLE
make Marlin renderer releases 0.9.4.6

### ISSUE THREAD

**Issue by bourgesl** [bourgesl/marlin-renderer#47]
Asap

**Comment by aaime** [comment]
On the topic, wondering about the integration of Marlin inside the JDK ([still using 0.9.1 it seems](https://github.com/bourgesl/marlin-renderer#release-history)). I'm guessing it's going to be a significant amount of work, or is there a more fundamental holdback (like, JDK core devs not happy with some of the recent changes?)

**Comment by bourgesl** [comment]
I upgraded jdk20 with latest marlin renderer 0.9.4.6 5 months ago!
