### ISSUE TITLE
Support for Java 7 with latest marlin?

### ISSUE THREAD

**Issue by dakcarto** [bourgesl/marlin-renderer#7]
Hi,

In the [release notes](https://github.com/bourgesl/marlin-renderer/releases) for versions 0.5.5 and 0.5.6 it states:

> This release is then recommended for JDK 1.8 only; for JDK 1.7, please use Marlin 0.4.5

But this warning goes away in the notes for versions 0.5.7+.

On the [How to Use](https://github.com/bourgesl/marlin-renderer/wiki/How-to-use) page it states support for:

> OpenJDK 1.7 & 1.8

This is a bit confusing. Does the latest, or any version > 0.4.5, work with a Java 7 runtime?

**Comment by bourgesl** [comment]
Larry,

I agree it is not really obvious:
All Marlin releases are compatible with OpenJDK and Oracle JDK 1.7 & 1.8.

> In the release notes for versions 0.5.5 and 0.5.6 it states:
>>
>> This release is then recommended for JDK 1.8 only; for JDK 1.7, please
use Marlin 0.4.5

In my benchmarks, it appeared at that time that the Unsafe variant (v0.5.5)
was a bit slower than the safe variant (v0.4.5) on jdk 1.7 so I recommended
the safe variant for jdk 1.7.

> But this warning goes away in the notes for versions 0.5.7+.
>
> On the How to Use page it states support for:
>>
>> OpenJDK 1.7 & 1.8
>
> This is a bit confusing. Does the latest, or any version > 0.4.5, work
with a Java 7 runtime?

I do not have time anymore to maintain several branches in synch (master vs
Unsafe) so I only provide Marlin releases based on the Unsafe branch.

Moreover Marlin v0.7.3 is now integrated in OpenJDK9, so please use only
the latest Marlin 0.7.3 release:
https://github.com/bourgesl/marlin-renderer/releases

PS: I will fix the wiki pages and release notes.

Regards,
Laurent

**Comment by dakcarto** [comment]
Thank you for the clarification.
